### ISSUE TITLE
About the weight

### ISSUE THREAD

**Issue by small-beebee** [wangyida/softpool#10]
Hi, I have tried my best to reproduce your results, but I cannot get a good result. I hope you can upload your pytorch version of the training weight file.

Thank you!

**Comment by wangyida** [comment]
Hi beebee,

The trained model would be saved as a single network.pth file with 4 models in our script, which makes it quite large in 622MB. You can use the codes in 'benchmark' folder to reproduce the reported results on complete3d dataset. We attach a screenshot for the numerical results on the README page.

Feel free to ask me again if you can not reproduce it with scripts in 'benchmark' folder. 

Yida
