### ISSUE TITLE
Concatenation operation

### ISSUE THREAD

**Issue by fabiopoiesi** [wangyida/softpool#4]
Hi,

https://github.com/wangyida/softpool/blob/f574058d2dc0489db18e3830fa3373918d72845a/pytorch/model.py#L123

I find difficult to understand this operation. Is this to concatenate the original 3D coordinate with the feature computed by the MLP? In practice a 3 + N_f vector?

Where is this explained in the paper?

Cheers

**Comment by wangyida** [comment]
Hi Fabio, it actually does not matter whether you concatenate the *part* with *x* or not, such concatenation is not used in the model described in paper. If you do not forward input partial scan, then you should change 3 + N_f into N_f directly
