### ISSUE TITLE
About "python setup.py install --user" in extensions/chamfer_dist

### ISSUE THREAD

**Issue by small-beebee** [wangyida/softpool#7]
root@f9adda5586c3:/mnt/txf/codes/SoftPoolNet/extensions/chamfer_dist# python setup.py install --user
running install
running bdist_egg
running egg_info
writing chamfer.egg-info/PKG-INFO
writing dependency_links to chamfer.egg-info/dependency_links.txt
writing top-level names to chamfer.egg-info/top_level.txt
reading manifest file 'chamfer.egg-info/SOURCES.txt'
writing manifest file 'chamfer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'chamfer' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/usr/include/python3.6m -c chamfer_cuda.cpp -o build/temp.linux-x86_64-3.6/chamfer_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/usr/local/cuda-10.0/bin/nvcc -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/usr/include/python3.6m -c chamfer.cu -o build/temp.linux-x86_64-3.6/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
chamfer.cu(160): error: a pointer to a bound function may only be used to call the function

chamfer.cu(160): error: type name is not allowed

chamfer.cu(160): error: expected an expression

chamfer.cu(160): error: a pointer to a bound function may only be used to call the function

chamfer.cu(160): error: type name is not allowed

chamfer.cu(160): error: expected an expression

chamfer.cu(161): error: a pointer to a bound function may only be used to call the function

chamfer.cu(161): error: type name is not allowed

chamfer.cu(161): error: expected an expression

chamfer.cu(161): error: a pointer to a bound function may only be used to call the function

chamfer.cu(161): error: type name is not allowed

chamfer.cu(161): error: expected an expression

chamfer.cu(163): error: a pointer to a bound function may only be used to call the function

chamfer.cu(163): error: type name is not allowed

chamfer.cu(163): error: expected an expression

chamfer.cu(163): error: a pointer to a bound function may only be used to call the function

chamfer.cu(163): error: type name is not allowed

chamfer.cu(163): error: expected an expression

chamfer.cu(164): error: a pointer to a bound function may only be used to call the function

chamfer.cu(164): error: type name is not allowed

chamfer.cu(164): error: expected an expression

chamfer.cu(164): error: a pointer to a bound function may only be used to call the function

chamfer.cu(164): error: type name is not allowed

chamfer.cu(164): error: expected an expression

chamfer.cu(216): error: a pointer to a bound function may only be used to call the function

chamfer.cu(216): error: type name is not allowed

chamfer.cu(216): error: expected an expression

chamfer.cu(216): error: a pointer to a bound function may only be used to call the function

chamfer.cu(216): error: type name is not allowed

chamfer.cu(216): error: expected an expression

chamfer.cu(217): error: a pointer to a bound function may only be used to call the function

chamfer.cu(217): error: type name is not allowed

chamfer.cu(217): error: expected an expression

chamfer.cu(217): error: a pointer to a bound function may only be used to call the function

chamfer.cu(217): error: type name is not allowed

chamfer.cu(217): error: expected an expression

chamfer.cu(218): error: a pointer to a bound function may only be used to call the function

chamfer.cu(218): error: type name is not allowed

chamfer.cu(218): error: expected an expression

chamfer.cu(218): error: a pointer to a bound function may only be used to call the function

chamfer.cu(218): error: type name is not allowed

chamfer.cu(218): error: expected an expression

chamfer.cu(220): error: a pointer to a bound function may only be used to call the function

chamfer.cu(220): error: type name is not allowed

chamfer.cu(220): error: expected an expression

chamfer.cu(220): error: a pointer to a bound function may only be used to call the function

chamfer.cu(220): error: type name is not allowed

chamfer.cu(220): error: expected an expression

chamfer.cu(221): error: a pointer to a bound function may only be used to call the function

chamfer.cu(221): error: type name is not allowed

chamfer.cu(221): error: expected an expression

chamfer.cu(221): error: a pointer to a bound function may only be used to call the function

chamfer.cu(221): error: type name is not allowed

chamfer.cu(221): error: expected an expression

chamfer.cu(222): error: a pointer to a bound function may only be used to call the function

chamfer.cu(222): error: type name is not allowed

chamfer.cu(222): error: expected an expression

chamfer.cu(222): error: a pointer to a bound function may only be used to call the function

chamfer.cu(222): error: type name is not allowed

chamfer.cu(222): error: expected an expression

60 errors detected in the compilation of "/tmp/tmpxft_000014de_00000000-6_chamfer.cpp1.ii".
error: command '/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1

I encountered the error when I run "python setup.py install --user" in "extensions/chamfer_dist". I don't solve it. Can you help me? Thank you!
My environmnet as follow:
torch:1.2.0
torchvision:0.4.0
gcc:7.5.0
cuda:10.0

**Comment by wangyida** [comment]
Can you try with the packege in [chamfer](https://github.com/wangyida/softpool/tree/master/pytorch/chamfer) folder. They are supposed to work in the same way and give you identical results.

**Comment by small-beebee** [comment]
Thank you very much! I get it!
